- name: firewall
  hosts: all
  sudo: true
  roles:
  - { role: postfix/base }
  - { role: postfix/master, when: ansible_hostname in groups.master }
  - { role: postfix/slave, when: ansible_hostname in groups.slave }
