- name: firewall
  hosts: all
  sudo: true
  roles:
  - { role: install, tags: [ 'install', 'master', 'slave' ] }
  - { role: master, tags: [ 'configure', 'master' ], when: ansible_hostname in groups.master }
  - { role: slave, tags: [ 'configure', 'slave' ], when: ansible_hostname in groups.slave }
