- name: restart postfix
  service: name=postfix state=restarted
- name: restart opendkim
  service: name=milter-opendkim state=restarted
- name: restart dovecot
  service: name=milter-opendkim state=restarted
