- set_fact:
    postfix_conf: /usr/local/etc/postfix/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    postfix_conf: /etc/postfix/
  when: ansible_system == 'Linux'

- name: Install Postfix (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=postfix state=latest force=yes
  notify: restart postfix
- name: Install Postfix (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=postfix state=present

- name: Enable Postfix (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^postfix_enable= line=postfix_enable=YES
- name: "Disable Sendmail (FreeBSD)"
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_enable= line=sendmail_enable=NO
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_submit_enable= line=sendmail_submit_enable=NO
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_outbound_enable= line=sendmail_outbound_enable=NO
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_msp_queue_enable= line=sendmail_msp_queue_enable=NO

- name: Paste main config
  notify: restart postfix
  template: src=main.cf dest={{ postfix_conf }}main.cf mode=0644

- name: Disable sendmail (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.slave
  lineinfile: dest=/etc/rc.conf regexp=sendmail_enable line=sendmail_enable=NO
- name: Disable sendmail (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.slave
  lineinfile: dest=/etc/rc.conf regexp=sendmail_submit_enable line=sendmail_submit_enable=NO
- name: Disable sendmail (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.slave
  lineinfile: dest=/etc/rc.conf regexp=sendmail_outbound_enable line=sendmail_outbound_enable=NO
- name: Disable sendmail (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.slave
  lineinfile: dest=/etc/rc.conf regexp=sendmail_msp_queue_enable line=sendmail_msp_queue_enable=NO

