- name: Install OpenDKIM (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=opendkim state=present
  notify: restart opendkim
- name: Enable OpenDKIM (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^milteropendkim_enable= line=milteropendkim_enable=YES
- name: Create OpenDKIM user
  user: >
    name=opendkim
    createhome=no
    comment=OpenDKIM
    shell=/usr/sbin/nologin
    home=/usr/local/etc/mail/
- name: Creates OpenDKIM directory
  file: >
    path=/var/db/opendkim
    state=directory
    owner=opendkim
    group=opendkim
    mode=0770
- name: Paste OpenDKIM config
  notify: restart opendkim
  template: >
    src=opendkim.conf
    dest=/usr/local/etc/mail/opendkim.conf
    owner=opendkim
    group=opendkim
    mode=0770

- name: Install Dovecot (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=dovecot,dovecot-sieve state=present
  notify: restart dovecot
- name: Enable Dovecot (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^dovecot_enable= line=dovecot_enable=YES
- name: Paste Dovecot config
  notify: restart dovecot
  template: >
    src=dovecot.conf
    dest=/usr/local/etc/dovecot.conf
    owner=dovecot
    group=dovecot
    mode=0770

- name: Paste Postfix config
  notify: restart postfix
  template: >
    src=main.cf
    dest=/usr/local/etc/postfix/main.cf
    owner=root
    group=wheel
    mode=0644
