- name: Create OpenDKIM user
  user: >
    name=opendkim
    createhome=no
    comment=OpenDKIM
    shell=/usr/sbin/nologin
    home=/usr/local/etc/mail/
- name: Creates OpenDKIM directory
  file: >
    path=/var/db/opendkim
    state=directory
    owner=opendkim
    group=opendkim
    mode=0770
- name: Paste OpenDKIM config
  notify: restart opendkim
  template: >
    src=opendkim.conf
    dest=/usr/local/etc/mail/opendkim.conf
    owner=opendkim
    group=opendkim
    mode=0770

- name: Paste Dovecot config
  notify: restart dovecot
  template: >
    src=dovecot.conf
    dest=/usr/local/etc/dovecot.conf
    owner=dovecot
    group=dovecot
    mode=0770

- name: Paste main Postfix config
  notify: restart postfix
  template: >
    src=main.cf
    dest=/usr/local/etc/postfix/main.cf
    owner=root
    group=wheel
    mode=0644

- name: Paste access Postfix config
  notify: restart postfix
  template: >
    src=access
    dest=/usr/local/etc/postfix/access
    owner=root
    group=wheel
    mode=0644
- name: Map access Postfix config
  shell: postmap /usr/local/etc/postfix/access

- name: Paste canonical Postfix config
  notify: restart postfix
  template: >
    src=canonical
    dest=/usr/local/etc/postfix/canonical
    owner=root
    group=wheel
    mode=0644
- name: Map access Postfix config
  shell: postmap /usr/local/etc/postfix/canonical

- name: Paste generic Postfix config
  notify: restart postfix
  template: >
    src=generic
    dest=/usr/local/etc/postfix/generic
    owner=root
    group=wheel
    mode=0644
- name: Map access Postfix config
  shell: postmap /usr/local/etc/postfix/generic

- name: Paste virtual Postfix config
  notify: restart postfix
  template: >
    src=virtual
    dest=/usr/local/etc/postfix/virtual
    owner=root
    group=wheel
    mode=0644
- name: Map access Postfix config
  shell: postmap /usr/local/etc/postfix/virtual

- name: Paste vmailbox Postfix config
  notify: restart postfix
  template: >
    src=vmailbox
    dest=/usr/local/etc/postfix/vmailbox
    owner=root
    group=wheel
    mode=0644
- name: Map access Postfix config
  shell: postmap /usr/local/etc/postfix/vmailbox
  
- name: Paste aliases Postfix config
  notify: restart postfix
  template: >
    src=aliases
    dest=/etc/aliases
    owner=root
    group=wheel
    mode=0644
- name: Map aliases Postfix config
  shell: newaliases
