- name: Create opendkim user
  user: >
    name=opendkim
    createhome=no
    comment=OpenDKIM
    shell=/usr/sbin/nologin
    home=/usr/local/etc/mail/
- name: Creates opendkim db
  file: >
    path=/var/db/opendkim
    state=directory
    owner=opendkim
    group=opendkim
    mode=0770
- name: Paste opendkim config
  notify: restart opendkim
  template: >
    src=opendkim.conf
    dest=/usr/local/etc/mail/opendkim.conf
    owner=opendkim
    group=opendkim
    mode=0770

- name: Paste dovecot config
  notify: restart dovecot
  template: >
    src=dovecot.conf
    dest=/usr/local/etc/dovecot/dovecot.conf
    owner=root
    group=wheel
    mode=0644
- name: Paste dovecot pam
  notify: restart dovecot
  template: >
    src=dovecot.pam
    dest=/usr/local/etc/pam.d/dovecot
    owner=root
    group=wheel
    mode=0644

- name: Paste main config
  notify: restart postfix
  template: >
    src=main.cf
    dest=/usr/local/etc/postfix/main.cf
    owner=root
    group=wheel
    mode=0644

- name: Paste mynetworks config
  notify: restart postfix
  register: mynetworks
  template: >
    src=mynetworks
    dest=/usr/local/etc/postfix/mynetworks
    owner=root
    group=wheel
    mode=0644
- name: Remove old mynetworks db
  when: mynetworks.changed
  shell: rm /usr/local/etc/postfix/mynetworks.db
- name: Map mynetworks config
  when: mynetworks.changed
  shell: postmap /usr/local/etc/postfix/mynetworks

- name: Paste access config
  notify: restart postfix
  register: access
  template: >
    src=access
    dest=/usr/local/etc/postfix/access
    owner=root
    group=wheel
    mode=0644
- name: Remove old access db
  when: access.changed
  shell: rm /usr/local/etc/postfix/access.db
- name: Map access config
  when: access.changed
  shell: postmap /usr/local/etc/postfix/access

- name: Paste canonical config
  notify: restart postfix
  register: canonical
  template: >
    src=canonical
    dest=/usr/local/etc/postfix/canonical
    owner=root
    group=wheel
    mode=0644
- name: Remove old canonical db
  when: canonical.changed
  shell: rm /usr/local/etc/postfix/canonical.db
- name: Map canonical config
  when: canonical.changed
  shell: postmap /usr/local/etc/postfix/canonical

- name: Paste generic config
  notify: restart postfix
  register: generic
  template: >
    src=generic
    dest=/usr/local/etc/postfix/generic
    owner=root
    group=wheel
    mode=0644
- name: Remove old generic db
  when: generic.changed
  shell: rm /usr/local/etc/postfix/generic.db
- name: Map generic config
  when: generic.changed
  shell: postmap /usr/local/etc/postfix/generic

- name: Paste virtual config
  notify: restart postfix
  register: virtual
  template: >
    src=virtual
    dest=/usr/local/etc/postfix/virtual
    owner=root
    group=wheel
    mode=0644
- name: Remove old virtual db
  when: virtual.changed
  shell: rm /usr/local/etc/postfix/virtual.db
- name: Map virtual config
  when: virtual.changed
  shell: postmap /usr/local/etc/postfix/virtual

- name: Paste vmailbox config
  notify: restart postfix
  register: vmailbox
  template: >
    src=vmailbox
    dest=/usr/local/etc/postfix/vmailbox
    owner=root
    group=wheel
    mode=0644
- name: Remove old vmailbox db
  when: vmailbox.changed
  shell: rm /usr/local/etc/postfix/vmailbox.db
- name: Map access config
  when: vmailbox.changed
  shell: postmap /usr/local/etc/postfix/vmailbox

- name: Paste aliases config
  notify: restart postfix
  register: aliases
  template: >
    src=aliases
    dest=/etc/aliases
    owner=root
    group=wheel
    mode=0644
- name: Map aliases config
  when: aliases.changed
  shell: newaliases
