- name: Install Postfix (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=postfix state=latest force=yes
  notify: restart postfix
- name: Install Postfix (CentOS)
  when: ansible_distribution == 'CentOS'
  yum: name=postfix state=latest
  notify: restart postfix
- name: Install Postfix (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=postfix state=present
  notify: restart postfix
- name: Enable Postfix (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^postfix_enable= line=postfix_enable=YES

- name: "Disable Sendmail #1 (FreeBSD)"
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_enable= line=sendmail_enable=NO
- name: "Disable Sendmail #2 (FreeBSD)"
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_submit_enable= line=sendmail_submit_enable=NO
- name: "Disable Sendmail #3 (FreeBSD)"
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_outbound_enable= line=sendmail_outbound_enable=NO
- name: "Disable Sendmail #4 (FreeBSD)"
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^sendmail_msp_queue_enable= line=sendmail_msp_queue_enable=NO

- name: Install OpenDKIM (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.master
  pkgng: name=opendkim state=present
  notify: restart opendkim
- name: Enable OpenDKIM (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.master
  lineinfile: dest=/etc/rc.conf regexp=^milteropendkim_enable= line=milteropendkim_enable=YES

- name: Install Dovecot (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.master
  pkgng: name=dovecot2 state=present
  notify: restart dovecot
- name: Enable Dovecot (FreeBSD)
  when: ansible_distribution == 'FreeBSD' and ansible_hostname in groups.master
  lineinfile: dest=/etc/rc.conf regexp=^dovecot_enable= line=dovecot_enable=YES
